### ISSUE TITLE
Cannot import name 'getComboPartition'

### ISSUE THREAD

**Issue by NEOherozzz** [Casyfill/pyCombo#1]
Hi,
I have successfully installed the pyCombo package. But when I import this module, it is reported like following.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\CodeSpace\src\pycombo\pyCombo\__init__.py", line 6, in <module>
    from pyCombo import getComboPartition as combo
ImportError: cannot import name 'getComboPartition'
```
The environment:
Python 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)] on win32.

Does anyone have a idea? Thanks in advance!

**Comment by Casyfill** [comment]
Hey @NEOherozzz  and sorry for the lack of support. I am pretty sure it is not relevant by now, but we completely revamped the code so it should both work and be pip-installable now:

https://pypi.org/project/pycombo/
