### ISSUE TITLE
outstrip C++ code using submodules

### ISSUE THREAD

**Issue by Casyfill** [Casyfill/pyCombo#21]
@Alexander-Belyi is the code in the main repo the same as here? 
It is probably a good idea to create a version tag there so I wouldn't link to the master.

**Comment by Alexander-Belyi** [comment]
Yes, it will be after the merge of a few typos fix from PR #20.
Thanks for the good suggestion. I've created a release here: https://github.com/Alexander-Belyi/Combo/releases/tag/v2.0
